version: '3.8'
services:
  web:
    build:
      context: ./
      target: dev
    depends_on:
      - postgres
    volumes:
      - .:/src
    command: yarn dev
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: development
  postgres:
    image: postgres:10.4
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: postgres
