version: '2'
services:
  web:
    build: .
    command: npm run start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://test@postgres/test
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: test
      POSTGRES_DB: test
